name: Continuous Integration

on:
  push:
    branches:
    - master

  pull_request:
    branches:
    - master

jobs:


  docs:
    # Deploy docs only when builds succeed

    runs-on: ubuntu-24.04

    if: github.ref == 'refs/heads/master'
      && github.event_name == 'push'
      && github.repository_owner == 'YBahaKama'

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with: { python-version: "3.12" }

    - name: Install m.css dependencies
      run: pip3 install jinja2 Pygments

    - name: Install Doxygen
      run: sudo apt-get update -q
        && sudo apt-get install doxygen -q -y
    
    - name: Build docs
      run: |
        cmake -S . -B build/docs-ci
        mv ./build/docs-ci/docs/Doxyfile ./
        cmake --build build/docs-ci --target docs  
        rm ./build/docs-ci/docs/xml/Doxyfile.xml
        python build/docs-ci/mcss/documentation/doxygen.py --no-doxygen build/docs-ci/docs/conf.py

    - name: Deploy docs
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/docs-ci/docs/html
